### ISSUE TITLE
lipid nomenclature

### ISSUE THREAD

**Issue by sofiahcosta** [ahmohamed/lipidr#10]
Lipids such as Coenzyme Q are not parsed because they don't follow the pattern 'CLS xx:x/yy:y'. Is there a way around this?

**Comment by ahmohamed** [comment]
Molecules that are not parsed will still be included in the differential analysis and plots. However, they will not have a class / FA chain lengths / unsaturation. If you want to have a separate class for these compounds, you can modify the `rowData` of the `LipidomicsExperiment` directly.

```r
other_classes = c('Cholesterol', 'Coenzyme Q',  'Ubiquinone')
rowData(data[other_classes, ])$Class = 'Other'
```

**Comment by ahmohamed** [comment]
Closing the issue. Please let me know if you have any other questions.
