### ISSUE TITLE
What is ACar?

### ISSUE THREAD

**Issue by Lucianabarros** [ahmohamed/lipidr#13]
Hello,

I did a LSEA analysis, but appeared an "ACar". Also, there was not a single significant result. I have several issues concerning lipids names parsing, and I`m trying to figure it out with the guys from the facility. 

Thank you again,

Luciana

**Comment by ahmohamed** [comment]
`lipidr` simply **splits** lipid names into their Class and Chain(s) components and then uses Chain information to calculate the total chain length and unsaturation. So, I assume your lipids included molecules named **ACar(xx:yy)**. Best guess it refers to Acyl Carnitine, but you should consult the software you used for matching lipids.
