### ISSUE TITLE
could not find function "plot_enrichment"

### ISSUE THREAD

**Issue by FernandoTobias** [ahmohamed/lipidr#15]
Hi, 

I'm having trouble obtaining the desired output for an enrichment analysis. I did the following:

> de_results <- de_analysis(d, Core - Monolayer)
Warning message:
Zero sample variances detected, have been offset away from zero 
> enrich_results = lsea(de_results)
Warning messages:
1: In fgsea::fgsea(pathways = pathways, stats = stats, minSize = minSize,  :
  You are trying to run fgseaSimple. It is recommended to use fgseaMultilevel. To run fgseaMultilevel, you need to remove the nperm argument in the fgsea function call.
2: In preparePathwaysAndStats(pathways, stats, minSize, maxSize, gseaParam,  :
  There are ties in the preranked stats (0.73% of the list).
The order of those tied genes will be arbitrary, which may produce unexpected results.
3: In serialize(data, node$con) :
  'package:stats' may not be available when loading
4: In serialize(data, node$con) :
  'package:stats' may not be available when loading
5: In serialize(data, node$con) :
  'package:stats' may not be available when loading
6: In serialize(data, node$con) :
  'package:stats' may not be available when loading
7: In serialize(data, node$con) :
  'package:stats' may not be available when loading
8: In serialize(data, node$con) :
  'package:stats' may not be available when loading
> significant_lipidsets(enrich_results)
$`Core - Monolayer`
[1] "Class_LPI"    "total_cs_0"   "Class_HexCer"

> plot_enrichment(de_results, significant_lipidsets(enrich_results), annotation="class")
Error in plot_enrichment(de_results, significant_lipidsets(enrich_results),  : 
  could not find function "plot_enrichment"

Thanks,
Fernando Tobias

**Comment by ahmohamed** [comment]
Can you check which lipidr version is installed. `plot_enrichment(annotation="class")` was added in version 2.4 to replace `plot_class_enrichment`.  If you're using older version, please update or use `plot_class_enrichment`.

**Comment by FernandoTobias** [comment]
Just updated to 2.4. It works now! Thanks.
