### ISSUE TITLE
How to extract the area matrix?

### ISSUE THREAD

**Issue by githubrudramani** [ahmohamed/lipidr#17]
Hi there,
I am having trouble with extracting the data matrix after doing the analysis. 
Do you suggest any function (like getAssayData) to get the data?
Thank you.

**Comment by ahmohamed** [comment]
Hi @githubrudramani,
LipidomicsExperiment that `lipidr` uses is a subclass of [SummarizedExperiment](https://rdrr.io/bioc/SummarizedExperiment/man/SummarizedExperiment-class.html). You can use `assay(data, "Area")` to extract the matrix.

**Comment by ahmohamed** [comment]
Closing the issue. Feel free to open if needed.
