### ISSUE TITLE
Dealing with multiple molecules with the same total chain length and unsaturation

### ISSUE THREAD

**Issue by FernandoTobias** [ahmohamed/lipidr#20]
Is there a way to generate heat maps of isomeric lipids in a similar way as `plot_chain_distribution(de_results)`?

**Comment by ahmohamed** [comment]
Can you clarify what you want to visualize? Currently, `plot_chain_distribution` summarizes isomeric lipids and display a number indicating the number of molecules summarized. How do you think isomeric lipids can be plotted?

**Comment by FernandoTobias** [comment]
Hello - 

At present, lipids species of the with the same total carbon # : double bond # ( PC (18:2_18:0) and PC (18:1_18:1) would be shown as an average between the two using `plot_chain_distribution`.

Is there a way to show them as separate points in a plot? I imagine it's possible. I have already indicated on my data_matrix.csv as two different species with an (1) or (2). For example, I have 5 PC lipids as PC (36:2) but are averaged as 1 in `plot_chain_distribution`

**Comment by ahmohamed** [comment]
Closing the issue, since I can't see any way to visualize all duplicates in the same plot. Feel free to reopen if you have any suggestions.
