### ISSUE TITLE
Question on the calculation of p values in volcano plots

### ISSUE THREAD

**Issue by vastevenson** [ahmohamed/lipidr#24]
Hi, 

I am looking on lipidr.org, however I am not able to find a page that describes how the p values for the volcano plots are being generated. Can you please clarify? 

Thank you! 

-Vincent

**Comment by ahmohamed** [comment]
Hi @vastevenson, methods are described in detail in the paper. Basically, we use `limma` package under the hood (which does a moderated t-test). The p values are adjusted for multiple hypothesis testing. 

PS: Can you please close the issues if you think they're resolved. Thanks!
