### ISSUE TITLE
no TG nor DG in list

### ISSUE THREAD

**Issue by jallebasi** [ahmohamed/lipidr#28]
Hi! 
Thanks for this package. I am wondering if it can be true that neither triglycerides nor diglycerides is included in the lipid reference list, and hence cannot be analyzed?

**Comment by ahmohamed** [comment]
Hi @jallebasi, Sorry for the late response. `lipidr` is completely agnostic to the lipid classes. This is determined by your dataset. As long as you names your lipid molecules using the convention CLS XX:YY, `lipidr` will automatically parse it and analyse it accordingly. Please refer to the vignette example here: https://www.lipidr.org/articles/examples/mw_integration.html where you'll find TGs and DGs included in the analysis.

Cheers,
Ahmed.
