### ISSUE TITLE
cannot be installed in MacOS RStudio

### ISSUE THREAD

**Issue by DavidGO464** [ahmohamed/lipidr#29]
Hi! I am trying to install it on RStudio for MacOS but it seems that cannot be instaled. any solutions
<img width="1196" alt="Screen Shot 2022-05-20 at 19 00 22" src="https://user-images.githubusercontent.com/87618961/169622610-45798bf9-07a1-40e0-b024-d32bf6c2d7fc.png">
?

**Comment by ahmohamed** [comment]
Hi David,
The issue is not related to lipidr, but it's a known issue for macos. You
just need to install gfortran library from here (
https://mac.r-project.org/tools/). You can choose the one matching to your
computer and is version.

Cheers.
Ahmed.
