### ISSUE TITLE
 argument "uq_expr" is missing

### ISSUE THREAD

**Issue by annikaghub** [ahmohamed/lipidr#30]
Hi Ahmed,
when I try to execute the function plot_samples, I receive the following error 
  Error in is_call(uq_expr, c("after_stat", "after_scale")) : 
    argument "uq_expr" is missing, with no default
Do you know what the problem could be?
Most of the other functions (like plot_lipidclass) are working fine.
Thanks and best,

Annika

**Comment by ahmohamed** [comment]
This issue was fixed in version 2.9.1. Could you please update lipidr and try again?

**Comment by annikaghub** [comment]
Perfect, thank you!
