### ISSUE TITLE
Add annotation with numeric scores

### ISSUE THREAD

**Issue by DavidGO464** [ahmohamed/lipidr#31]
Can I add an annotation with numeric values?

for instance "risk score: 0,1,2,3" :

Sample       Risk Score
Sample 1 - - -   0
Sample 2 - - -   1
Sample 3 - - -   2
Sample 4 - - -   1
.
.
etc

or it is just for categorical data?

thanks in advance for your answer.

**Comment by ahmohamed** [comment]
Hi David,

You definitely can. Please see this example of using continuous variable to
model cancer stages.
https://www.lipidr.org/articles/examples/mw_integration.html#supervised-multivariate-analysis-with-continuous-response-variable

Cheers.
