### ISSUE TITLE
Batch effect

### ISSUE THREAD

**Issue by DavidGO464** [ahmohamed/lipidr#32]
Hi

I wonder how lipidr can manage the batch effect. 
I have a dataset of more than 1500 lipids and 200+ samples, but this is a merge of 6 batches.

thanks for your answer

**Comment by ahmohamed** [comment]
Hi David,
Sounds exciting! 

Two options, both are borrowed from limma package.
1. [`limma::removeBatchEffects`](https://rdrr.io/bioc/limma/man/removeBatchEffect.html) which corrects your numerical matrix for batch effects.
2. Include `batch` in your design matrix (https://www.lipidr.org/reference/de_analysis.html): 
```r
design <- model.matrix(~ batch + group, data = colData(data_normalized))
de_design(data, design)
```
