### ISSUE TITLE
lipid name parsing for class(O+P-chain)

### ISSUE THREAD

**Issue by Summer1019** [ahmohamed/lipidr#35]
Hi Ahmed,

It seems that lipidr can parse molecules named with class(P-chain) or class(O-chain), which is quite good, but not with class(O+P-chain). sorry if it is a silly question, I'm new to lipidomics.

thanks for your time,
Yao

**Comment by ahmohamed** [comment]
Thanks Yao, and sorry for the late response. I'm not quite familiar with O+P chains or their naming conventions. Can you send an example from lipidmaps https://www.lipidmaps.org/ ? 

Cheers,
Ahmed.

**Comment by Summer1019** [comment]
Hi Ahmed,

Sorry for the late response. I found that it's because the normal phase column can not chromatographically separate the nature of the ether species (alkyl/alkenyl) and have this O+P. The reversed-phase column can separate them and have the “P-” prefix for an alkenyl ether substituent, and the "O-" prefix for alkyl. And our mass spectrum center used both normal phase and reversed phase which generated both “P-”, “O-”, and “O+P-”.

Thanks for your time.
Yao
