### ISSUE TITLE
Volcano plot eBayes f or t statistic

### ISSUE THREAD

**Issue by annikaghub** [ahmohamed/lipidr#36]
Hi Ahmed,

when creating a volcano plot (plot_results_volcano), lipidr calls the eBayes function. I don't understand whether a moderated f or t statistic is computed/used. Can you tell me which one it is?
Thank you for your time!
Best,

Annika

**Comment by ahmohamed** [comment]
`plot_results_volcano` simply plot the results from `limma::topTable` (adj.P.Val and logFC). While I'm not sure exactly of the details, as per `limma` docs (https://rdrr.io/bioc/limma/man/toptable.html) below:

> If coef has a single value, then the moderated t-statistics and p-values for that coefficient or contrast are used. If coef takes two or more values, the moderated F-statistics for that set of coefficients or contrasts are used.

P-values should be calculated based on moderated t statistics if you use contrasts (`de_analysis`), or when you specify a single `coef` in `de_design` (examples [here](https://www.lipidr.org/articles/examples/mw_integration.html#two-group-comparison) and [here](https://www.lipidr.org/articles/examples/mw_integration.html#factorial-analysis)). Alternatively, if you perform multigroup comparison (ANOVA-like), moderated F statistics will be used to calculate P-values ([here](https://www.lipidr.org/articles/examples/mw_integration.html#multi-group-comparison)).

You can view the `topTable` output from `de_design` and `de_analysis`, and examine whether a `t` or `F` statistic column is included, to be sure what was used for p-values calculations. You can also try [LipidSuite](https://suite.lipidr.org/) Univariate analysis tab, which displays both the volcano plot along with the `topTable` interactively. There you'll see a `t` column when performing `two-group comparison` and `F` column when `MultiGroup ANOVA` is used.

Hope this answers your question. If not, feel free to reopen the issue.
Cheers,
Ahmed.

**Comment by annikaghub** [comment]
Perfect, thank you!
