### ISSUE TITLE
Normalized?

### ISSUE THREAD

**Issue by DavidGO464** [ahmohamed/lipidr#41]
Just to make sure, 

when `as_lipidomics_experiment` asks if the data is "normalized", it is **NOT** referring to "standardization",  right?

with "standardization", I mean a mean of 0 (zero) and SD of 1. 

I ask this because in data science it is pretty common to use both terms interchangeably 

![Screen Shot 2022-10-12 at 12 36 09](https://user-images.githubusercontent.com/87618961/195399447-610fb148-67df-4906-ac21-178903adf9d3.png)

**Comment by ahmohamed** [comment]
Normalization is defined as used in 'omics analysis, which means that samples have similar distributions. It doesn't imply zero-centered means or unit variance scaling. The latter is not needed for differential analysis.

NB: some internal functions in `lipidr` will perform scaling where needed. One example is the `mva` function for PCA and OPLS. You don't need to worry about that though.
