### ISSUE TITLE
could not find function "plot_enrichment"

### ISSUE THREAD

**Issue by xiaowenchenjax** [ahmohamed/lipidr#44]
Dear Developer,
 Thank you for developing R package. I installed lipidr version 2.12.0, however, I got an error 
"Error in plot_enrichment(de_results, significant_lipidsets(enrich_results),  : 
  could not find function "plot_enrichment""

when I run on the example data.

Could you give me some clue? Thanks

**Comment by ahmohamed** [comment]
1. Make sure you load the package: `library(lipidr)`
2. If still not working, check which `lipdir` version are you using with:

```r
installed.packages()["lipidr", "Version"]
```

The current version is 2.12. It might help to update the package
