### ISSUE TITLE
a question about lipid name

### ISSUE THREAD

**Issue by xiaowenchenjax** [ahmohamed/lipidr#46]
Hi Ahmed,
Thank you for developing this great tool. 
I have a question about the lipid name. Based on the tutorial, the lipid name must be CLS xx:y. I am a new for lipidomics data. what do xx and y mean? I saw some lipids' name like this "DG 14:0/18:1/0:0", what do those number mean? 
If I have a lipid name, such as "
(+/-)14,15-EET_1"  and "9-HpODE(2)", how I can convert those names to the format lipidr requires?
Thank you.
Look forward to your reply.

**Comment by ahmohamed** [comment]
`lipidr` needs lipids named according to LipidMaps abbreviated nomenclature, as in the example you mentioned "DAG 14:0/18:1". The nomenclature consists of two parts, lipid class (`DAG`) and lipid chain information (`14:0/18:1`). 

Lipid chain information lists all chains attached to a molecule separated by slash `/`, so in our case, we have 2 chains `14:0` and `18:1`. The two numbers indicate chain length (number of carbons) and unsaturation (number of double bonds). `18:1` means 18 carbons length and a single double bond.

Depending on how you setup and acquire your lipidomics data, certain lipid classes may be present or absent. In your case, the examples you listed are `fatty acyls`, which can be abbreviated as `FA XX:Y`. You can refer to the 2 links below from LipidMaps.
 
https://www.lipidmaps.org/databases/lmsd/LMFA03080005
https://www.lipidmaps.org/data/LMSDRecord.php?LMID=LMFA02000286

Converting lipid names, especially for the not-so-common ones, is a quite a hard task. There are a few tools listed here: https://www.lipidmaps.org/resources/tools/nomenclature, but I didn't have any luck getting them to work. [apps.lifs-tools.org/goslin](https://apps.lifs-tools.org/goslin) is also another alternative that may work for some of the lipids. Feel free to reach to the authors of these tools if needed (github repos below).

https://github.com/lifs-tools/goslin-webapp
https://github.com/SysMedOs/LipidLynxX


The last resort is to use `lipidr` with invalid lipid names. You'll be able to perform all the steps in the workflow except where lipid class is needed (lipid class enrichment, some of the plots). Let me know if this doesn’t work for you.

**Comment by xiaowenchenjax** [comment]
Hi Ahmed,
Thank you for your quick reply. It is clear and helpful.
By the way, if my data is signal intensity, is it good to use lipidr? Thanks.

**Comment by ahmohamed** [comment]
I assume you mean MS signal intensity, right? If so, `lipidr` should be ideal for your case.

**Comment by xiaowenchenjax** [comment]
Yes, thank you!
