### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by kristinapedersen** [ahmohamed/lipidr#47]
Dear Ahmohamed,

Thank you for a great tool and easy to follow examples. 

I am new to R and to lipids so I am sorry if this is problem i should have been able to fix myself, i feel like i might be missing an update in R or something. However, when i run my own dataset as well as when i follow along in your example https://www.lipidr.org/articles/examples/mw_integration.html "Data mining using lipidr" you have uploaded I keep get an error i do not understand when i run the scripts: plot_samples(d, "tic") or plot_samples(d, "boxplot")

and the error i get for both of them is:
Error in is_call(uq_expr, c("after_stat", "after_scale")) : 
  argument "uq_expr" is missing, with no default

Hope you can help, 
Kind regards 
Kristina

**Comment by ahmohamed** [comment]
Hi Kristina,

Please see #30 for details. Let me know if it's not working.
